
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public class Viewall extends javax.swing.JInternalFrame {

    /**
     * Creates new form Viewall
     */
    
    
    public Viewall() {
        FlatLightLaf.setup();
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI UIE = (BasicInternalFrameUI)this.getUI();
        UIE.setNorthPane(null);
        
        Vehicallist view = new Vehicallist ();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(view).setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vehicalInspection = new javax.swing.JButton();
        vehicalList = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        vehicalInspection.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        vehicalInspection.setForeground(new java.awt.Color(51, 51, 51));
        vehicalInspection.setText("Vehicle inspection and update ");
        vehicalInspection.setContentAreaFilled(false);
        vehicalInspection.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        vehicalInspection.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vehicalInspection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicalInspectionActionPerformed(evt);
            }
        });

        vehicalList.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        vehicalList.setForeground(new java.awt.Color(51, 51, 51));
        vehicalList.setText("View all");
        vehicalList.setContentAreaFilled(false);
        vehicalList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        vehicalList.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vehicalList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicalListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(vehicalList, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vehicalInspection, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(937, Short.MAX_VALUE))
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicalInspection, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicalList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vehicalInspectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicalInspectionActionPerformed
        // TODO add your handling code here:
        try{
        
            Vehicaldetails view = new Vehicaldetails();
            jDesktopPane1.removeAll();
            jDesktopPane1.add(view).setVisible(true);
        }
        catch(Exception e){
        
        }
        
    }//GEN-LAST:event_vehicalInspectionActionPerformed

    private void vehicalListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicalListActionPerformed
        // TODO add your handling code here:
        try{
        
            Vehicallist view = new Vehicallist();
            jDesktopPane1.removeAll();
            jDesktopPane1.add(view).setVisible(true);
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_vehicalListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton vehicalInspection;
    private javax.swing.JButton vehicalList;
    // End of variables declaration//GEN-END:variables
}
